### ISSUE TITLE
Align and/or Justify Components.

### ISSUE THREAD

**Issue by nyakagwafred** [BuildForSDGCohort2/team-185-frontend#15]
@brysonwaisi please align or justify both the `expenseSummary`  and` incomeSummary` components to the center of the parent `Container` element. Currently, these elements are justified to the left.

![image](https://user-images.githubusercontent.com/51993500/94238852-99ee0680-ff19-11ea-9780-63f5bab75e13.png)

**Comment by osmankbk** [comment]
Hello! Can I please work on this?

**Comment by nyakagwafred** [comment]
> Hello! Can I please work on this?

 Are you on this team?
